server:
  port: 8801
  servlet:
    context-path: /common

eureka:
  client: service-url.default-zone=http://localhost:8761/eureka

spring:
  application:
    name: common-server
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    password: common
    username: common
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#    database-platform: org.hibernate.dialect.Oracle12cDialect

integration:
  minio:
    access-key: admin
    secret-key: admin@2024
    url: http://localhost:9000


# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true



