server:
  port: 8762

app:
  api-prefix: /api/v1

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: common-service
          uri: http://localhost:8801
          predicates:
            - Path=/common/**
        - id: user-service
          uri: http://localhost:8802
          predicates:
            - Path=/user-service/**
        - id: work-service
          uri: http://localhost:8803
          predicates:
            - Path=/work/**

      discovery:
        locator:
          enabled: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

