server:
  port: 8762

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: common-service
          uri: http://localhost:8801
          predicates:
            - Path=/common/**
        - id: user-service
          uri: http://localhost:8802
          predicates:
            - Path=/user-service/**

      discovery:
        locator:
          enabled: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

